### PR TITLE
Add git-lfs support to collect-logs.sh

### PR DESCRIPTION
**Pull request by isherman**

### CODE REVIEW

**Comment by isherman** [comment]
@mabitter would love to use this PR to test the latest "checkout and build" workflow with you on our call

**Review by ethanrublee — APPROVED** [review]

**Comment by isherman** [comment]
Issues encountered on Matthew computer:
 - bash -x failure
 - ssh-add issue
 - git config --global issue

**Comment by isherman** [comment]
in tractor-logs:
```
git config user.email `hostname`
git config user.name `hostname`
```

**Comment by isherman** [comment]
Verified working with Michael.

**Pull request merged**
