### PR TITLE
Support blobstore browsing and editing

### PR DESCRIPTION
**Pull request by isherman**

### CODE REVIEW

**Comment by isherman** [comment]
Remaining: 
- [ ] Shrink program-specific logic as small as possible
- [ ] Support "tailing" programs
- [ ] Harden file browsing
- [ ] Repeated int form
- [ ] Form formatting
- [ ] Support POSTing a change to the blobstore
- [ ] Standardize Visualizer interface
- [ ] Do some renaming
- [ ] Add blob browser modal for resource selection in forms

**Comment by isherman** [comment]
Ready for review. This expanded into quite a large PR -- once I wanted to support Blobstore editing, in addition to Blobstore browsing, it meant revisiting how we dealt with forms throughout. Forms were previously hardcoded into the program logic -- now they live in the visualizer object for a given type, and are composable.

Other things to note:
- Improved the Program "plugin" API and the Visualizer "plugin" API. They are both ready for other people to start contributing plugins so I can get some feedback on the developer experience.
- Blobstore visualization/editing currently hardcodes the types of data expected at different directory paths. We discussed persisting `Any`s as a way around this, but hoping this can be addressed in a follow-up PR.
- Program visualization now looks more like the Oscilloscope, so you can "tail" program progress
- The R/W file server is a fork of `net/http/fs.go`, mainly so I could piggyback on the work they've done handling static file serving edge cases, limiting the ability to "escape" the virtual filesystem root, etc. I had some ideas this morning about composing this functionality rather than forking it, but requires a bit of exploration.
- One new proto definition, in `resource.proto`, used by the R/W file server.

Once this is merged, one straightforward followup task is to make our services load from `BLOBSTORE_ROOT/configurations/tractor.config` on start.

Have done some testing, but haven't tested all calibration programs end-to-end.

**Comment by isherman** [comment]
## Built-in visualization of data types in the visualization registry


## Standard browser handling of common file types (mp4, jpg, etc)


## Editing of configuration files

**Review by ethanrublee — APPROVED** [review]
Looks great.

Will try to add a visualization and a program myself in a followup to see how it goes.

I tested apriltag rig calibration, base to camera calibration, and video dataset collection on my desktop and worked as expected.

**Pull request merged**
